version: "3.8"

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile.database
    image: library_db
    container_name: library_db_container
    environment:
      POSTGRES_DB: library 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - library-network

  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    volumes:
      - pg-admin-data:/var/lib/pgadmin
    depends_on:
      - database
    networks:
      - library-network

  server: 
    build: 
      context: .
      dockerfile: ./server/Dockerfile.server
    image: library_server
    container_name: library_server_container 
    depends_on:
      - database
    networks:
      - library-network

volumes:
  db-data:
  pg-admin-data:

networks:
  library-network: 
    driver: bridge 