# version: "3.9"

services:
  database:
    image: postgres:latest
    volumes:
      - ./database/query:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    # networks:
    #   - library
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  # pgadmin:
  #   container_name: container-pgadmin
  #   image: dpage/pgadmin4:6
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@email.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #     - PGADMIN_LISTEN_PORT=5050  
  #   depends_on:
  #     - database
  #   ports:
  #     - "5050:5050"
  #   networks:
  #     - library
  #   volumes:
  #     - pg-admin-data:/var/lib/pgadmin

  server:
    build:
      context: ./server
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: library
      DB_USER: postgres
      DB_PASSWORD: postgres
    # command: make clean_server server
    volumes:
      - ./database:/app/database
      - ./config:/app/config
      - ./Makefile:/app/Makefile
    networks:
      - library
    ports:
      - "8080:8080"

volumes:
  db_data:
  pg-admin-data:

networks:
  library:
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: 127.0.0.0/24