services:
  database:
    ports:
      - "5432:5432"
    build:
      context: .
      dockerfile: Dockerfile.database
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - db_data:/var/lib/postgresql/data
    
  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - database
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

  # server:
  #   hostname: 127.0.0.1
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.server
  #   depends_on:
  #     - database
  #   environment:
  #     DB_HOST: "127.0.0.1"
  #     DB_PORT: 5432
  #     DB_NAME: library
  #     DB_USER: postgres
  #     DB_PASSWORD: admin
  #   ports:
  #     - "8080:8080"

  # client:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.client
  #   depends_on:
  #     - server

volumes:
  db_data:

# networks:
#   mynetwork:
#     ipam:
#       config:
#         - subnet: 127.10.0.0/16