# Dockerfile per il database
FROM postgres:latest

# Imposta le variabili d'ambiente per la configurazione del database
ENV POSTGRES_DB=library
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=admin

# Esponi la porta del database
EXPOSE 5432
