#define MAX_REQUEST_BUFFER_LENGTH 1024

enum RequestType {
    SIGN_UP,
    SIGN_IN,
    EXPLORE_CATALOG,
    SEARCH_AVAILABLE_BOOKS, 
    SEARCH_BOOK_BY_NAME, 
    SEARCH_BOOK_BY_GENRE,
    LOAN_PROCEDURE_START, 
    ADD_TO_LOAN, 
    LOAN_CHECKOUT, 
    RETURN_BOOK, 
};
