#pragma once
#define MAX_REQUEST_BUFFER_LENGTH 1024

enum RequestType {
    SIGN_UP,
    SIGN_IN,
    EXPLORE_CATALOG,
    SEARCH_AVAILABLE_BOOKS, 
    SEARCH_BOOK_BY_NAME, 
    SEARCH_BOOK_BY_GENRE,
    MAKE_LOAN, 
    GET_LOAN_BOOKS, 
    RETURN_BOOK,
    CHANGE_LOAN_DURATION,
    GET_EXPIRED_LOAN,
    GET_CURRENT_LOAN_DURATION, 
};
